### ISSUE TITLE
请问小程序 async/await的实现方式

### ISSUE THREAD

**Issue by lvyuanying** [hufeng/mppack#8]
非常感谢大神提供的一套小程序打包插件，正如readme里所说的，gulp用plugin-transform-runtime打包出来小程序没办法支持，请问大神是如何解决 async/await 这个问题的。

**Comment by hufeng** [comment]
1. 可以使用typescript 然后降级到es2015
2. 自己整合babel插件解决这个问题

目前我正在大范围的重构这个项目 😆

**Comment by hufeng** [comment]
![image](https://user-images.githubusercontent.com/533008/49714135-bd818780-fc86-11e8-8ad7-dfe1a77652a5.png)

更好的性能，更好的开发方式

**Comment by hufeng** [comment]
@lvyuanying https://github.com/hufeng/mppack/issues/39
